//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenkatFinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class availabilitySunday
    {
        public string facilityID { get; set; }
        public Nullable<short> Slot9To10 { get; set; }
        public Nullable<short> slot10to11 { get; set; }
        public Nullable<short> slot11to12 { get; set; }
        public Nullable<short> slot12to13 { get; set; }
        public Nullable<short> slot13to14 { get; set; }
        public Nullable<short> slot14to15 { get; set; }
        public Nullable<short> slot15to16 { get; set; }
        public Nullable<short> slot16to17 { get; set; }
        public Nullable<short> slot117to18 { get; set; }
        public int uniqid { get; set; }
    
        public virtual Facility Facility { get; set; }
    }
}
