//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenkatFinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.availabilityFridays = new HashSet<availabilityFriday>();
            this.availabilityMondays = new HashSet<availabilityMonday>();
            this.availabilitySaturdays = new HashSet<availabilitySaturday>();
            this.availabilitySundays = new HashSet<availabilitySunday>();
            this.availabilityThursdays = new HashSet<availabilityThursday>();
            this.availabilityTuesdays = new HashSet<availabilityTuesday>();
            this.availabilityWednesdays = new HashSet<availabilityWednesday>();
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public string FacilityID { get; set; }
        public string FacilityType { get; set; }
        public string FacilityDescription { get; set; }
    
        public virtual ICollection<availabilityFriday> availabilityFridays { get; set; }
        public virtual ICollection<availabilityMonday> availabilityMondays { get; set; }
        public virtual ICollection<availabilitySaturday> availabilitySaturdays { get; set; }
        public virtual ICollection<availabilitySunday> availabilitySundays { get; set; }
        public virtual ICollection<availabilityThursday> availabilityThursdays { get; set; }
        public virtual ICollection<availabilityTuesday> availabilityTuesdays { get; set; }
        public virtual ICollection<availabilityWednesday> availabilityWednesdays { get; set; }
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
