//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenkatFinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public string MemberID { get; set; }
        public string MemberName { get; set; }
        public string phoneNumber { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
    }
}
